### PR TITLE
Bug Fix: OFT-62440/OFT-62449 - Cannot display person card for indiduals ...

### LINKED ISSUE #20: Persons with quotes in their name break data-cmd-data attribute
When fsModules.fsPersonGender is given an object:

{
gender: "Male"
id: "LVJF-29Q"
lifeSpan: "Deceased"
name: "Talanthalas &quot;Tanis&quot; Half-Elven"
relationshipId: "MGBM-BHG"
title: "Talanthalas &quot;Tanis&quot; Half-Elven"
}

The resulting data-cmd-data attribute becomes garbled with unescaped quotes:

data-cmd-data="{"id":"LVJF-29Q","name":"Talanthalas "Tanis" Half-Elven","gender":"Male"}"

Which results in a JavaScript error when clicked on.

See: 
https://beta.familysearch.org/tree/#view=ancestor&person=LVJF-29Q

frontier/tree/assets/js/modules/CollapsibleFamilyMembersGadget/main/collapsibleFamilyMembers/view/ChildView.js, line 34 (this is used in the Parents and Siblings section of the family members gadget, for the children)

### PR DESCRIPTION
**Pull request by skye2k2**
...with quotes or apostrophes in their name

Fixes #20

### CODE REVIEW

File: assets/js/fsPerson/viewModels/fsPersonVitals.viewModel.js [hunk 1]
```diff
@@ -34,6 +34,14 @@ function fsPersonVitalsViewModel(scope) {
     scope.nameConclusionStyle = 'fs-person-vitals__name--' + (''+scope.person.nameConclusion.details.style).toLowerCase();
   }
 
+  if(scope.person.name) {
+    scope.person.name = scope.person.name
+      .replace(/"/g, "&quot;")
+      .replace(/'/g, "&#39;")
+      .replace(/</g, "&lt;")
+      .replace(/>/g, "&gt;");
+  }
```
Comment (lambertsteven) [inline assets/js/fsPerson/viewModels/fsPersonVitals.viewModel.js]: FS.htmlEncode() does this for you.

    scope.person.name = FS.htmlEncode(scope.person.name);

Comment (skye2k2) [inline assets/js/fsPerson/viewModels/fsPersonVitals.viewModel.js]: No it doesn't. Single-quotes are not handled.

Comment (lambertsteven) [inline assets/js/fsPerson/viewModels/fsPersonVitals.viewModel.js]: Interesting. I can't get it to fail when I play around with different string combinations, maybe it fails when passed a particular name? Also, are there really names with angle brackets? That just seems strange to my lack of knowledge.
